"use client";
import { Cast, LoaderCircle, Square } from "lucide-react";
import { useEffect, useState } from "react";
import type { ArchiveMedia } from "@/lib/archive";
import { useCast, type CastOptions } from "./cast-provider";
export function CastButton({ items, options, compact = false, overlay = false, placement = "right", inColumn = false, onBeforeCast, getAirPlayVideo, onMenuOpenChange }: { items: ArchiveMedia[]; options?: CastOptions; compact?: boolean; overlay?: boolean; placement?: "left" | "right"; inColumn?: boolean; onBeforeCast?: () => void; getAirPlayVideo?: () => HTMLVideoElement | null; onMenuOpenChange?: (open: boolean) => void }) {
  const cast = useCast(); const [help, setHelp] = useState(false); const active = cast.connected && (options?.mode === "presentation" ? cast.mode === "presentation" : cast.mode === "single" && items.some(media => media.id === cast.activeId));
  useEffect(() => { if (active) setHelp(false); }, [active]);
  useEffect(() => { onMenuOpenChange?.(help && cast.supported); }, [help, cast.supported, onMenuOpenChange]);
  if (!cast.supported) return null;
  return <div className={inColumn ? "media-surface media-cast-overlay relative z-10" : overlay ? "media-surface media-cast-overlay absolute top-3 z-30 " + (placement === "left" ? "left-3" : "right-3") : "media-surface relative"}><div className="flex items-center gap-2"><button type="button" aria-label={active ? "Casting media to " + cast.device : options?.mode === "presentation" ? "Cast favorites presentation" : "Cast this item"} aria-disabled={(cast.ready && !cast.supported) || cast.busy} title={cast.reason} onClick={event => { event.stopPropagation(); onBeforeCast?.(); if (!cast.available) { setHelp(!help); return; } if (!cast.busy) { if (overlay && active && cast.transport !== "airplay") { setHelp(!help); return; } setHelp(true); void cast.castItems(items, { ...options, openPicker: true, airPlayVideo: cast.transport === "airplay" ? getAirPlayVideo?.() : undefined }); } }} className={overlay ? "media-overlay-button " + (active ? "text-studio-soft" : "text-white/75") : "inline-flex min-h-11 min-w-11 items-center justify-center gap-2 rounded-full border bg-black/80 px-3 text-sm " + (active || cast.available ? "border-[#d4af37]/50 text-studio-soft" : "border-white/20 text-white/40")}>{cast.busy ? <LoaderCircle className={overlay ? "h-4 w-4 animate-spin" : "h-4 w-4 animate-spin"} /> : <Cast className={overlay ? "h-4 w-4" : "h-4 w-4"} />}{compact || overlay ? null : cast.busy ? "Preparing…" : active ? "On " + cast.device : options?.mode === "presentation" ? "Cast presentation" : "Cast"}</button>{active && !overlay ? <button onClick={cast.stop} aria-label="Stop casting" title="Stop casting" className="grid min-h-11 min-w-11 place-items-center rounded-full border border-white/20 text-white/70"><Square className="h-3 w-3 fill-current" /></button> : null}</div>{help || (!overlay && cast.error) ? <div className={overlay ? "absolute top-full mt-2 w-64 max-w-[calc(100vw-4rem)] rounded-lg border border-white/20 bg-black/95 p-3 shadow-xl " + (placement === "left" ? "left-0" : "right-0") : "mt-2 max-w-xs"}><p role="status" className="text-xs leading-relaxed text-studio-soft">{cast.error || (active && overlay ? "Playing on " + cast.device : cast.reason)}</p>{overlay && active ? <button onClick={() => { cast.stop(); setHelp(false); }} className="mt-2 mr-4 min-h-11 text-xs text-white underline">Stop casting</button> : null}{overlay ? <button onClick={() => setHelp(false)} className="mt-2 min-h-9 text-xs text-white underline" aria-label="Dismiss casting message">Dismiss</button> : null}</div> : null}</div>;
}
