"use client";
import { ChevronLeft, ChevronRight, Pause, Play, RotateCcw, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { flushSync } from "react-dom";
import { mediaUrl } from "@/lib/archive";
import type { FavoriteMedia } from "@/lib/favorite-media";
import { useModal } from "@/lib/use-modal";
import { FavoriteButton } from "./favorite-button";
import { CastButton } from "./cast-button";
import { useCast } from "./cast-provider";
import { useMediaSwipe } from "@/lib/use-media-swipe";

export function FavoritesPresentation({ items, initialIndex, autoplay, photoSeconds, loop, onClose }: { items: FavoriteMedia[]; initialIndex: number; autoplay: boolean; photoSeconds: number; loop: boolean; onClose: () => void }) {
  const cast = useCast(); const casting = cast.connected && cast.mode === "presentation"; const remotePlayback = cast.connected && (cast.mode === "presentation" || cast.mode === "single"); const remoteRef = useRef(false); const wasRemote = useRef(false); remoteRef.current = remotePlayback || cast.busy;
  const modal = useModal(onClose); const [index, setIndex] = useState(initialIndex); const [running, setRunning] = useState(autoplay); const [finished, setFinished] = useState(false); const [imageReady, setImageReady] = useState(""); const [audioBlocked, setAudioBlocked] = useState(false); const [error, setError] = useState("");
  const video = useRef<HTMLVideoElement | null>(null); const media = items[index];
  const next = useCallback((automatic = false) => { video.current?.pause(); if (index + 1 < items.length) { setFinished(false); if (casting) cast.jump(items[index + 1].id); flushSync(() => setIndex(index + 1)); } else if (automatic && loop) { if (items.length === 1 && video.current) { video.current.currentTime = 0; void video.current.play().catch(() => setAudioBlocked(true)); } else flushSync(() => setIndex(0)); } else if (automatic) { setRunning(false); setFinished(true); } else onClose(); }, [index, items, loop, onClose, casting, cast.jump]);
  function previous() { video.current?.pause(); setFinished(false); if (casting) cast.jump(items[Math.max(0, index - 1)].id); flushSync(() => setIndex(value => Math.max(0, value - 1))); }
  const swipe = useMediaSwipe({ onPrevious: previous, onNext: () => next(), canStart: event => !(event.target as HTMLElement).closest("button, input") && !(media.mediaType === "VIDEO" && !remotePlayback && event.clientY > (video.current?.getBoundingClientRect().bottom || event.currentTarget.getBoundingClientRect().bottom) - 80) });
  const attachVideo = useCallback((element: HTMLVideoElement | null) => { if (video.current && video.current !== element) { video.current.pause(); video.current.muted = true; } video.current = element; if (!element) return; setAudioBlocked(false); setError(""); if (remoteRef.current) { element.pause(); element.muted = true; return; } element.muted = false; void element.play().catch(async e => { if (video.current !== element || e.name === "AbortError") return; if (e.name === "NotAllowedError") { setAudioBlocked(true); element.muted = true; try { await element.play(); } catch { /* Native controls remain available. */ } } else setError("Unable to play this video. Use the video controls or continue to the next item."); }); }, []);
  useEffect(() => { if (!running || remotePlayback || cast.busy || media.mediaType === "VIDEO" || imageReady !== media.id) return; const timer = setTimeout(() => next(true), photoSeconds * 1000); return () => clearTimeout(timer); }, [running, remotePlayback, cast.busy, media.id, media.mediaType, imageReady, next, photoSeconds]);
  useEffect(() => { const active = remotePlayback || cast.busy; if (active) { video.current?.pause(); if (video.current) video.current.muted = true; } else if (wasRemote.current && video.current) attachVideo(video.current); wasRemote.current = active; }, [remotePlayback, cast.busy, attachVideo]);
  useEffect(() => { if (!casting) return; const active = items.findIndex(item => item.id === cast.activeId); if (active >= 0) setIndex(active); setRunning(!cast.paused && !cast.ended); setFinished(cast.ended); }, [casting, cast.activeId, cast.paused, cast.ended, items]);
  useEffect(() => { if (cast.connected && cast.mode === "single" && cast.activeId !== media.id && !cast.busy) void cast.castItems([media]); }, [cast.connected, cast.mode, cast.activeId, cast.busy, cast.castItems, media]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.target as HTMLElement).matches("input, select, video")) return; if (event.key === "ArrowRight") { event.preventDefault(); next(); } if (event.key === "ArrowLeft") { event.preventDefault(); previous(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  function toggle() { if (casting) { cast.togglePlayback(); return; } setFinished(false); if (running) { setRunning(false); video.current?.pause(); } else { setRunning(true); if (video.current && !remotePlayback) { video.current.muted = false; void video.current.play().catch(() => setAudioBlocked(true)); } } }
  function restart() { if (casting) { void cast.castItems(items, { mode: "presentation", photoSeconds, loop, startIndex: 0 }); return; } setFinished(false); setRunning(true); if (video.current) video.current.currentTime = 0; flushSync(() => setIndex(0)); void video.current?.play().catch(() => setAudioBlocked(true)); }
  return <div ref={modal} role="dialog" aria-modal="true" aria-label="Favorites presentation" tabIndex={-1} className="fixed inset-0 z-50 overflow-y-auto bg-black/[.97] px-4 pb-8 pt-20 sm:px-8"><button onClick={onClose} className="fixed right-4 top-4 z-[60] inline-flex min-h-12 items-center gap-2 rounded-full border border-white/30 bg-black/85 px-4 text-sm font-semibold text-white"><X className="h-5 w-5" /> Close presentation</button><div className="mx-auto max-w-6xl"><div {...swipe} className="relative flex min-h-[45dvh] touch-pan-y items-center justify-center rounded-2xl border border-white/10 bg-black"><CastButton items={[media]} overlay />
      {media.mediaType === "VIDEO" ? <video key={media.id} ref={attachVideo} src={mediaUrl(media.playbackFile || media.fileName)} poster={media.thumbnail ? mediaUrl(media.thumbnail) : undefined} controls={!remotePlayback} playsInline preload="auto" className="max-h-[70dvh] w-full object-contain" onPlay={event => { if (remoteRef.current) { event.currentTarget.pause(); event.currentTarget.muted = true; } }} onEnded={() => { if (running && !remotePlayback) next(true); }} onError={() => setError("This video could not load. Continue to the next item or try again.")} /> : <img key={media.id} src={mediaUrl(media.fileName)} alt="Favorite presentation media" draggable={false} onLoad={() => { setImageReady(media.id); setError(""); }} onError={() => setError("This photo could not load. Continue to the next item.")} className="max-h-[70dvh] w-full object-contain" />}
    </div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><button disabled={index === 0} onClick={previous} className="grid min-h-12 min-w-12 place-items-center rounded-full border border-white/25 disabled:opacity-20" aria-label="Previous favorite"><ChevronLeft /></button><span className="px-2 text-sm text-white/65">{index + 1} / {items.length}</span><button onClick={() => next()} className="grid min-h-12 min-w-12 place-items-center rounded-full border border-white/25" aria-label="Next favorite"><ChevronRight /></button></div><div className="flex flex-wrap items-center gap-2"><FavoriteButton mediaId={media.id} /><CastButton items={items} options={{ mode: "presentation", photoSeconds, loop, startIndex: index }} />{finished ? <button onClick={restart} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#d4af37] px-4 font-semibold text-black"><RotateCcw className="h-4 w-4" /> Replay</button> : <button onClick={toggle} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[#d4af37]/45 px-4 text-[#f4d77e]">{running ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}{running ? "Pause presentation" : "Play presentation"}</button>}</div></div>
    {remotePlayback ? <p className="mt-4 text-sm text-[#f4d77e]">Media is playing on {cast.device || "your TV"}. <button onClick={cast.togglePlayback} className="ml-2 min-h-11 underline">{cast.paused ? "Play on TV" : "Pause on TV"}</button></p> : null}
    {audioBlocked && !remotePlayback ? <button onClick={() => { if (video.current) { video.current.muted = false; void video.current.play().then(() => setAudioBlocked(false)).catch(() => setError("Tap Play in the video controls to enable sound.")); } }} className="mt-4 min-h-11 rounded-full bg-[#d4af37] px-4 font-semibold text-black">Enable sound</button> : null}{error ? <p role="status" className="mt-4 text-[#f4d77e]">{error}</p> : null}{finished ? <p className="mt-4 text-white/60">Presentation finished.</p> : null}
    <p className="mt-8 font-editorial text-2xl text-white/85">{new Date(media.takenAt).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}</p><p className="mt-3 whitespace-pre-wrap text-lg leading-relaxed text-white/65">{media.caption}</p></div></div>;
}
