"use client";
import { ArrowDown, ArrowUp, ArrowLeft, Play, Star } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { flushSync } from "react-dom";
import { mediaUrl } from "@/lib/archive";
import type { FavoriteMedia } from "@/lib/favorite-media";
import { FavoriteButton } from "./favorite-button";
import { useFavorites } from "./favorites-provider";
import { FavoritesPresentation } from "./favorites-presentation";
import { CastButton } from "./cast-button";
import { ThemeButton } from "./theme-button";

export function FavoritesView() {
  const favorites = useFavorites(); const [items, setItems] = useState<FavoriteMedia[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [retry, setRetry] = useState(0);
  const [seconds, setSeconds] = useState(6); const [loop, setLoop] = useState(false);
  const [presentation, setPresentation] = useState<{ items: FavoriteMedia[]; index: number; autoplay: boolean } | null>(null);
  useEffect(() => {
    if (!favorites.ready) return;
    if (!favorites.ids.length) { setItems([]); setLoading(false); return; }
    const controller = new AbortController(); setLoading(true); setError("");
    fetch("/api/favorites/media", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: favorites.ids }), signal: controller.signal }).then(async response => { if (!response.ok) throw new Error("Unable to retrieve favorites"); return await response.json() as { items: FavoriteMedia[] }; }).then(data => setItems(data.items)).catch(e => { if (e.name !== "AbortError") setError("Favorites could not be loaded. Your saved list is still on this device."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [favorites.ready, favorites.ids, retry]);
  function open(index: number, autoplay: boolean) { flushSync(() => setPresentation({ items: [...items], index, autoplay })); }
  return <main className="page-glow min-h-screen px-4 py-8 sm:px-8 lg:px-12"><div className="mx-auto max-w-[1740px]">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/" className="inline-flex min-h-11 items-center gap-2 text-sm text-white/60"><ArrowLeft className="h-4 w-4" /> Back to the archive</Link><ThemeButton /></div>
    <header className="my-8 border-b border-white/10 pb-8"><p className="mb-3 flex items-center gap-2 text-xs uppercase tracking-[.22em] text-studio-accent"><Star className="h-4 w-4" /> Your personal collection</p><h1 className="font-editorial text-5xl sm:text-7xl">Favorites</h1><p className="mt-4 max-w-2xl leading-relaxed text-white/55">Individual photos and videos you love. Arrange them, revisit them, or play them as a presentation.</p><p className="mt-2 text-xs text-white/40">Saved on this browser and device. Clearing browser storage removes this list.</p></header>
    {favorites.error || error ? <p role="status" className="mb-6 text-studio-soft">{favorites.error || error} {error ? <button onClick={() => setRetry(value => value + 1)} className="min-h-11 underline">Retry</button> : null}</p> : null}
    {items.length ? <section className="mb-8 flex flex-wrap items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-5" aria-label="Presentation settings"><button onClick={() => open(0, true)} disabled={loading} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-studio-fill px-5 font-semibold text-black disabled:opacity-40"><Play className="h-4 w-4 fill-current" /> Play presentation</button><CastButton items={items} options={{ mode: "presentation", photoSeconds: seconds, loop }} /><label className="flex items-center gap-3 text-sm text-white/70">Photo duration<select value={seconds} onChange={e => setSeconds(Number(e.target.value))} className="min-h-11 rounded-lg border border-white/15 studio-panel px-3 text-white">{[3,6,10,15,30].map(value => <option key={value} value={value}>{value} seconds</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={loop} onChange={e => setLoop(e.target.checked)} /> Repeat presentation</label><span className="text-sm text-white/40">{items.length} items</span></section> : null}
    {loading ? <p role="status" className="py-12 text-white/55">Opening your favorites…</p> : !items.length ? <div className="py-20 text-center"><Star className="mx-auto mb-5 h-8 w-8 text-studio-accent" /><h2 className="font-editorial text-3xl">Make a collection of your own.</h2><p className="mt-4 text-white/55">Tap the star on any photo or video in the archive.</p><Link href="/" className="mt-6 inline-flex min-h-12 items-center rounded-full border border-[#d4af37]/40 px-5 text-studio-soft">Explore the wall</Link></div> : <section className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-4" aria-label="Favorite media">{items.map((media, index) => <article key={media.id} className="overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]"><button onClick={() => open(index, false)} className="media-surface relative block aspect-[4/5] w-full bg-black" aria-label={"View favorite " + (index + 1)}><img src={mediaUrl(media.thumbnail || media.fileName)} alt="Favorite archive memory" loading="lazy" className="h-full w-full object-cover" /><span className="absolute left-3 top-3 rounded-full border border-white/20 bg-black/75 px-3 py-1 text-xs text-white">{media.mediaType === "VIDEO" ? "▶ Video" : "Photo"}</span><span className="absolute bottom-3 left-3 rounded-full bg-black/75 px-3 py-1 text-xs">{index + 1}</span></button><div className="p-4"><p className="font-editorial text-2xl">{new Date(media.takenAt).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}</p><p className="mt-2 line-clamp-2 text-base leading-relaxed text-white/65">{media.caption}</p><div className="mt-4 flex items-center justify-between gap-2"><FavoriteButton mediaId={media.id} /><div className="flex gap-1"><button aria-label={"Move favorite " + (index + 1) + " earlier"} disabled={index === 0} onClick={() => favorites.move(media.id, -1)} className="grid min-h-11 min-w-11 place-items-center rounded-full border border-white/15 text-white/70 disabled:opacity-20"><ArrowUp className="h-4 w-4" /></button><button aria-label={"Move favorite " + (index + 1) + " later"} disabled={index === items.length - 1} onClick={() => favorites.move(media.id, 1)} className="grid min-h-11 min-w-11 place-items-center rounded-full border border-white/15 text-white/70 disabled:opacity-20"><ArrowDown className="h-4 w-4" /></button></div></div></div></article>)}</section>}
    {!loading && !error && favorites.ids.length > items.length ? <p className="mt-6 text-sm text-white/50">Some saved items have been removed from the archive. <button className="min-h-11 text-studio-soft underline" onClick={() => favorites.ids.filter(id => !items.some(item => item.id === id)).forEach(favorites.remove)}>Remove unavailable favorites</button></p> : null}
    {presentation ? <FavoritesPresentation items={presentation.items} initialIndex={presentation.index} autoplay={presentation.autoplay} photoSeconds={seconds} loop={loop} onClose={() => setPresentation(null)} /> : null}
  </div></main>;
}
